### ISSUE TITLE
Binary wheels seem to be missing for py38 windows and mac

### ISSUE THREAD

**Issue by christopher-hesse** [ICRAR/crc32c#15]
These would be nice to have, as python 3.9 is almost out.  If getting this to work with travis/appveyor is tough, the new github actions does windows/mac/linux and is pretty slick.

**Comment by rtobar** [comment]
Yes, I've been so far using a mix of Appveyor for Windows (3.8 wasn't available when I first set it up), a very old (10.8.5) MacOS machine that supports only up to python 3.7, and the `manylinux` docker image for the linux binaries. So yes, quite chaotic. I known there are good solutions out there for simplifying and automatic this, I just haven't bothered setting it up yet.

Maybe I'll give the GitHub actions a try and see how it goes. The Windows Travis support could also be an option, given that I already have MacOS and Linux jobs in there.

Feel free to contribute a solution; I'll keep this in the background of my mind, but probably won't get immediate attention.

**Comment by christopher-hesse** [comment]
@rtobar I contributed a solution over here: https://github.com/ICRAR/crc32c/pull/16

**Comment by rtobar** [comment]
#16, as contributed by @christopher-hesse, is now merged. It provides binary wheels for macos_10.9+, manylinux1, manylinux2010, win32 and amd64 platforms in all major CPython/PyPy versions. A new 2.0.1 release will be out soon in PyPI with the set of new wheels.

In the process of testing and accepting #16 a bug was found in the generation of source distributions, introduced in v1.6. This will also be fixed in 2.0.1.
