### ISSUE TITLE
Fallback to Python does not work on Python 3.8 (possibly others?)

### ISSUE THREAD

**Issue by haard** [ICRAR/crc32c#17]
Running with a missing dll on Windows, Python 3.8 leads to 
```  
File "lib\site-packages\crc32c\__init__.py", line 29, in <module>
TypeError: category must be a Warning subclass, not 'str'
```
which breaks the fallback.

**Comment by rtobar** [comment]
@haard thanks for reporting this problem.

You mention a missing DLL. Could you please provide some details on how you installed the package, its version, and what DLL is missing from where? Our code doesn't use the `warnings` module, so it's not clear to me where the error comes from. It also makes me suspect you might be using actually a package different from this one (in that case definitely give ours a go!).

Note also that there is absolutely no python code in this package. What the code would be failing to fallback to is the *software* implementation (still in C), and not the *python* implementation (no such thing). But there's no such warning on that case

Also, what CPU are you running on? Windows doesn't support that many architectures, so I'm curious how you fell into this situation in the first place. And unless you explicitly set `CRC32C_SW_MODE` to `none`, the fallback to software should happen silently (since version 2.0).

**Comment by haard** [comment]
Thanks for the quick response! The root cause for my error was a packaging issue (PyInstaller) easily resolved and not related to crc32c as such. 

Further investigations made me find out that another package pulls not https://pypi.org/project/crc32c/ but Google's crc32c wrapper - and that package had the issue but fixed it 20 days ago: https://github.com/googleapis/python-crc32c/commit/b50f43e7bc40d91ccdade9ccc577a93c0ed05f3a#diff-cfa1424c9fe65df40b68626996162b0c

So, no errors or issues on your side, sorry for taking up your time!

**Comment by rtobar** [comment]
No problem, thanks for clarifying the situation, I'm glad you found out the actual problem.
