### ISSUE TITLE
copyright and license for file crc32c_arm64.c is illogical

### ISSUE THREAD

**Issue by jonassmedegaard** [ICRAR/crc32c#19]
File <crc32c_arm64.c> contains this at the top:
> // Copyright 2017 The CRC32C Authors. All rights reserved.
> // Use of this source code is governed by a BSD-style license that can be
> // found in the LICENSE file. See the AUTHORS file for names of contributors.

There is however no file <AUTHORS>, and file <LICENSE> does not contain a BSF-style license.

It seems this file is derived from https://github.com/google/crc32c where those references make sense.

Please make sense of the information - e.g. by adding files <AUTHORS.google_crc32c> and <LICENSE.BSD> (as a snapshot of those upstream files as they were when you forked the code) and updating references to point to those files actually existing within your code project.

**Comment by jonassmedegaard** [comment]
I notice now that you've mentioned in <README.md> that some parts are "Copyright 2017 The CRC32C Authors".

I guess you don't consider yourself "CRC32C Authors" but that was not clear to me - and I imagine that others would easily be confused as well.

I suggest that you also update that paragraph to clarify who "The CRC32C Authors" are - e.g. by referencing same AUTHORS* file as suggested above.

**Comment by rtobar** [comment]
@jonassmedegaard Thanks for pointing out the inconsistencies.

> It seems this file is derived from https://github.com/google/crc32c where those references make sense.

Yes, that's indeed where it's taken from. This is mentioned in the file though: https://github.com/ICRAR/crc32c/blob/4a0fca4959247db2498903a92e6ca0fd878084d0/crc32c_arm64.c#L11-L12

I initially thought that this would be enough for people to also make sense of the information about license and authors, but the license indeed requires it to be distributed alongside the derived work; I'll amend that.

> I guess you don't consider yourself "CRC32C Authors" but that was not clear to me

The phrase "CRC32C Authors" was copied verbatim from google's crc32c package, and is what they use in their copyright notices (also in their license file). It thus refers to google's crc32c package, not this one, as you found out. And as is turns out, since a few weeks ago I actually am an author on their package too.

I agree with the suggestion of adding a snapshot of the AUTHORS file from the time I forked. I'll do that too.

**Comment by rtobar** [comment]
The copyright and licencing situation of this package has been further clarified in #20 to include a more precise picture of where each piece of external code comes from, who are their authors, and what are their licenses. The changes are now incorporated onto the `master` branch, so we can close this.
