### ISSUE TITLE
Change access to software implementation

### ISSUE THREAD

**Issue by nlgranger** [ICRAR/crc32c#5]
Hi, thank you for this library,

Using an environment variable to unlock the software implementation is not really the idiomatic python style. Would you please consider an alternative that doesn't require to fiddle with os.environ in the import section of the source code.
Maybe a `fallback=False` argument or a global module variable or a wrapper function which selects the backend automatically?

**Comment by rtobar** [comment]
Hi,

Thanks for the feedback. Please note that you don't need to set the environment variable *in your code* (I guess that's what you are doing, given that you mention `os.environ`); you can set it in the environment where your programs gets launched from without having to modify your code. See [here](https://github.com/ICRAR/crc32c/blob/master/.travis.yml#L41-L46) and [here](https://github.com/ICRAR/crc32c/blob/master/.appveyor.yml#L50-L56) for examples.

I want the module to be first and foremost about the hardware implementation (it was until very recently **only** about it), without giving users false expectations regarding the speed. That's why it is designed to fail at import time when SSE4.2 is not found (except now when `CRC32C_SW_MODE=1`). In other words, an ImportError translates directly to lack of hardware support, and I'd like to keep it that way. The alternative would be to fail later when the user calls `crc32`, but failing earlier gives the possibility to users to take action sooner in their code.

Having said that, and if you still want to enforce the usage of the software implementation from within your code, then yes, I'm happy to consider an alternative mechanism to set this preference, but that still follows the "fail to import" rule. Using the `fallback` argument implies a successful import of the package in the first place, which in turn would imply hardware support, therefore beating the purpose of the flag in the first place (and I'd like to keep `crc32c.crc32` signature-compatible with `binascii.crc32` anyways). Following that logic, the global module variable and the wrapper function both imply hardware support too.

**Comment by nlgranger** [comment]
I see, thank you for the explanation. The environment variable is not controlled in the case of a library which is then redistributed to other users. May I suggest to split the hard and soft implementations into two package then (if that is not too annoying to maintain it that way)?
It would make an elegant fallback for those who want it while keeping the separation explicit:
```python
try:
    import crc32c
except ImportError:
    import crc32c_sw as crc32c
```

**Comment by rtobar** [comment]
Hi! You could still do

```python
try:
    import crc32c
except ImportError:
    os.environ['CRC32C_SW_MODE'] = '1'
    import crc32c
```

without having to have two split packages. I have to admit that I didn't really think of a use case like yours, and I see how the code above is unnecessarily complex. Maybe I could add a different value to the `CRC32C_SW_MODE` environment variable (say, `auto`) so at import time the software method is selected as a fallback if there is no hw support. You then would have to do it like this:

```python
os.environ['CRC32C_SW_MODE'] = 'auto'
import crc32c
```

You'd still have to set the environment variable, but the import would be guaranteed to work and give you the best possible implementation. Is that an acceptable solution?

**Comment by awicenec** [comment]
Rodrigo,

have you have tried to use the Intel compiler rather than gcc? If yes, have you seen any effect?

-Andreas

**Comment by nlgranger** [comment]
That's good to me, it was just a suggestion.

**Comment by rtobar** [comment]
I've added support for specifying `auto` with the `CRC32C_SW_MODE` environment variable as stated above, and updated the documentation accordingly.
