### ISSUE TITLE
Mac wheels for 1.7

### ISSUE THREAD

**Issue by kislyuk** [ICRAR/crc32c#9]
Thanks again for this great package. I just wanted to point out that pre-built wheels (which are immensely useful) are missing for Mac OS in the latest released version, 1.7. Hopefully they can be added.

**Comment by rtobar** [comment]
Hi Andrey,

Thanks for pointing that out, I have just created and added them. Could you give them a try, and hopefully mark this as resolved if everything is fine?

Just to clarify, even though you added a MacOS build in our Travis CI, I'm still generating the MacOS wheels myself under a more controlled environment to ensure maximum portability across MacOS versions. They basically should be usable under any MacOS 10.6+ version. I do that by using the official [MacOS packages](https://www.python.org/downloads/mac-osx/) instead of using homebrew's or mac port's versions of python, which would yield wheels that are not as portable.

**Comment by rtobar** [comment]
Closing as the wheels seem to be fine.
